INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Catlin', 'Tirrey', 'ctirrey0');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Mommy', 'Bonus', 'mbonus1');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Flint', 'Shrubsall', 'fshrubsall2');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Kelsi', 'Burlay', 'kburlay3');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Ives', 'McCloid', 'imccloid4');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Curcio', 'Kun', 'ckun5');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Pincus', 'Dur', 'pdur6');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Stephenie', 'Ciobutaru', 'sciobutaru7');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Cammi', 'Edgcumbe', 'cedgcumbe8');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Daron', 'Managh', 'dmanagh9');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Tod', 'Dugood', 'tdugooda');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Maddie', 'Peggram', 'mpeggramb');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Elspeth', 'Swatradge', 'eswatradgec');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Dennie', 'Gue', 'dgued');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Joell', 'Ramshaw', 'jramshawe');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Merrill', 'Huyche', 'mhuychef');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Obed', 'Bailes', 'obailesg');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Maritsa', 'Windsor', 'mwindsorh');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Kata', 'Maypes', 'kmaypesi');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Early', 'Heugle', 'eheuglej');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Waylin', 'Gwilt', 'wgwiltk');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Obie', 'Arnau', 'oarnaul');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Wendel', 'Trays', 'wtraysm');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Yelena', 'Morfey', 'ymorfeyn');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Miltie', 'Brightman', 'mbrightmano');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Lanie', 'Biggin', 'lbigginp');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Muffin', 'Darthe', 'mdartheq');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Lorrayne', 'Freezor', 'lfreezorr');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Reynolds', 'Braddon', 'rbraddons');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Willem', 'Buterton', 'wbutertont');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Beniamino', 'Duckwith', 'bduckwithu');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Sancho', 'O''Moylan', 'somoylanv');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Barbaraanne', 'Priddey', 'bpriddeyw');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Colene', 'Speare', 'cspearex');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Normand', 'Guilloux', 'nguillouxy');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Herve', 'MacCosty', 'hmaccostyz');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Daryn', 'Blackway', 'dblackway10');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Faulkner', 'Prosch', 'fprosch11');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Janenna', 'Childes', 'jchildes12');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Shayna', 'Dyke', 'sdyke13');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Ingunna', 'O''Corrigane', 'iocorrigane14');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Lorri', 'Matyasik', 'lmatyasik15');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Tanhya', 'Varga', 'tvarga16');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Leoine', 'Franklyn', 'lfranklyn17');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Jenna', 'Chevis', 'jchevis18');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Tatiana', 'Golsby', 'tgolsby19');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Hally', 'Tarbett', 'htarbett1a');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Angela', 'McQuarrie', 'amcquarrie1b');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Chicky', 'Johns', 'cjohns1c');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Pebrook', 'Farthin', 'pfarthin1d');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Stacee', 'McCourt', 'smccourt1e');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Eldon', 'Pounsett', 'epounsett1f');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Keriann', 'Bannerman', 'kbannerman1g');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Garrick', 'Lorentz', 'glorentz1h');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Anny', 'Bainton', 'abainton1i');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Jenilee', 'Cranfield', 'jcranfield1j');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Isaak', 'Vizor', 'ivizor1k');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Darius', 'Micklewright', 'dmicklewright1l');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Melvyn', 'Walburn', 'mwalburn1m');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Lambert', 'Hasloch', 'lhasloch1n');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Kaila', 'Brabbs', 'kbrabbs1o');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Emmeline', 'Eastbury', 'eeastbury1p');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Ollie', 'Marqyes', 'omarqyes1q');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Virgie', 'Ormerod', 'vormerod1r');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Hollyanne', 'Tolossi', 'htolossi1s');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Bram', 'Flay', 'bflay1t');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Cherlyn', 'Mohring', 'cmohring1u');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Joli', 'Chantree', 'jchantree1v');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Misty', 'Docherty', 'mdocherty1w');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Marielle', 'Rarity', 'mrarity1x');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Abbot', 'Semens', 'asemens1y');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Klara', 'Plumbe', 'kplumbe1z');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Georgeta', 'Terbruggen', 'gterbruggen20');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Derron', 'Bail', 'dbail21');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Claudelle', 'Wroath', 'cwroath22');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Lissy', 'Briton', 'lbriton23');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Jimmie', 'Dargan', 'jdargan24');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Rancell', 'Braikenridge', 'rbraikenridge25');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Mata', 'Zorer', 'mzorer26');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Amory', 'Fierman', 'afierman27');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Hobart', 'Colmer', 'hcolmer28');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Thatcher', 'Wix', 'twix29');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Jeremias', 'Abate', 'jabate2a');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Krisha', 'Batting', 'kbatting2b');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Ingram', 'Curston', 'icurston2c');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Jourdain', 'Tegler', 'jtegler2d');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Douglas', 'Buxy', 'dbuxy2e');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Cori', 'Wyles', 'cwyles2f');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Charmine', 'Filippozzi', 'cfilippozzi2g');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Tove', 'Guido', 'tguido2h');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Bianca', 'Banbury', 'bbanbury2i');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Saree', 'Hush', 'shush2j');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Padgett', 'Dobell', 'pdobell2k');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Tessa', 'Aubri', 'taubri2l');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Angie', 'Livett', 'alivett2m');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Hannah', 'Orr', 'horr2n');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Mirilla', 'Moncur', 'mmoncur2o');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Codi', 'Gomez', 'cgomez2p');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Celeste', 'Prescott', 'cprescott2q');
INSERT INTO CUSTOMER (first_name, last_name, username) VALUES ('Cobby', 'Eivers', 'ceivers2r');

INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Muller-Dickens', 'Romania', 'Cluj-Napoca', 'Cluj', 'Memorandumului, 23');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Luettgen-Kunze', 'Romania', 'Cluj-Napoca', 'Cluj', 'Dorobantilor, 5');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Wiza, Dicki and O''Conner', 'Romania', 'Cluj-Napoca', 'Cluj', 'Aurel Vlaicu, 32');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Marvin Group', 'Romania', 'Cluj-Napoca', 'Cluj', 'Bucium, 44');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Crist and Sons', 'Romania', 'Brasov', 'Brasov', 'Eroilor, 10');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Hoppe Group', 'Romania', 'Brasov', 'Brasov', 'Nicolae Titulescu, 27');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Maggio-Turner', 'Romania', 'Brasov', 'Brasov', 'Iuliu Maniu, 81');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Welch, Bashirian and Cartwright', 'Romania', 'Brasov', 'Brasov', 'Dorobantilor, 43');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Barrows-Mosciski', 'Romania', 'Brasov', 'Brasov', 'Mihail Kogalniceanu, 105');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Kozey-Turcotte', 'Romania', 'Bucuresti', 'Bucuresti', 'Mihail Kogalniceanu, 105');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Langosh-Stracke', 'Romania', 'Bucuresti', 'Bucuresti', 'Maresal Constantin Prezan, 59');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('O''Kon, Legros and Marquardt', 'Romania', 'Bucuresti', 'Bucuresti', 'Metalurgiei, 3');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Adams, Sporer and Gleichner', 'Romania', 'Bucuresti', 'Bucuresti', 'Marasesti, 40');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Blanda Group', 'Romania', 'Iasi', 'Iasi', 'Muzicescu, 12');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Russel LLC', 'Romania', 'Iasi', 'Iasi', 'Arcu, 20');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Barrows Inc', 'Romania', 'Iasi', 'Iasi', 'Silvestru, 44');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Kuhn, Emard and Hessel', 'Romania', 'Iasi', 'Iasi', 'Anastasie Panu, 39');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Johnson-Rowe', 'Romania', 'Timisoara', 'Timis', 'Paris, 23');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Deckow-Boehm', 'Romania', 'Timisoara', 'Timis', 'Sfantul Ioan, 18');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Johnston and Sons', 'Romania', 'Timisoara', 'Timis', 'Republicii, 24');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Von LLC', 'Romania', 'Timisoara', 'Timis', 'Vasile Lucaciu, 19');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Brekke Inc', 'Romania', 'Dej', 'Cluj', 'Marasesti, 9');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Greenfelder-Senger', 'Romania', 'Arad', 'Arad', 'Andrei Saguna, 29');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Kub-Brakus', 'Romania', 'Arad', 'Arad', 'George Cosbuc, 14');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Bogan and Sons', 'Romania', 'Arad', 'Arad', 'Corneliu Coposu, 43');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Hettinger LLC', 'Romania', 'Arad', 'Arad', 'Dornei, 1');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Willms LLC', 'Romania', 'Turda', 'Cluj', 'General Dragalina, 8');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Prohaska, Sawayn and Kuhlman', 'Romania', 'Turda', 'Cluj', 'Potaissa, 30');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Abbott, Hickle and Grant', 'Romania', 'Alba-Iulia', 'Alba', 'Decebal, 84');
INSERT INTO LOCATION (name, country, city, county, street) VALUES ('Swaniawski-Sauer', 'Romania', 'Alba-Iulia', 'Alba', 'Gheorghe Dija, 5');

INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (7, 16, 'Romania', 'Satu Mare', 'Satu Mare', 'Liviu Rebreanu, 13', '2018-01-19 07:44:40');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (1, 7, 'Romania', 'Satu Mare', 'Satu Mare', 'Rodnei, 20', '2018-01-19 07:44:40');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (3, 38, 'Romania', 'Cluj-Napoca', 'Cluj', 'Eroilor, 14', '2018-01-19 08:00:20');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (8, 43, 'Romania', 'Cluj-Napoca', 'Cluj', 'Avran Iancu, 71', '2018-01-19 10:48:33');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (2, 49, 'Romania', 'Cluj-Napoca', 'Cluj', 'Dunarii, 55', '2018-01-19 01:38:23');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (8, 21, 'Romania', 'Bucuresti', 'Bucuresti', 'Progresului, 14', '2018-01-19 08:00:20');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (6, 11, 'Romania', 'Bucuresti', 'Bucuresti', 'Progresului, 83', '2018-01-19 01:38:23');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (1, 25, 'Romania', 'Bucuresti', 'Bucuresti', 'Matei Basarab, 2', '2018-01-19 10:40:45');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (6, 15, 'Romania', 'Bucuresti', 'Bucuresti', 'Turda, 33', '2018-01-19 19:20:49');
INSERT INTO ORDERS (location_id, customer_id, country, city, county, street, date) VALUES (9, 8, 'Romania', 'Satu Mare', 'Satu Mare', 'Liviu Rebreanu, 61', '2018-01-19 10:40:45');

INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Carbonated Water - Lemon Lime', 'Red Pepper Paste');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Salmon - Atlantic, Skin On', 'Vector Energy Bar');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Stainless Steel Cleaner Vision', 'Tomatoes - Heirloom');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Worcestershire Sauce', 'Cheese - Goat With Herbs');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Radish - Black, Winter, Organic', 'Tea - Apple Green Tea');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Garbage Bags - Clear', 'Energy Drink - Franks Pineapple');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Lemon Grass', 'Vector Energy Bar');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Lamb - Whole, Frozen', 'Pork - Chop, Frenched');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Clementine', 'Butter - Salted');
INSERT INTO PRODUCT_CATEGORY (name, description) VALUES ('Juice - Tomato, 10 Oz', 'Soupcontfoam16oz 116con');

INSERT INTO SUPPLIER (name) VALUES ('Snaptags');
INSERT INTO SUPPLIER (name) VALUES ('Innojam');
INSERT INTO SUPPLIER (name) VALUES ('Podcat');
INSERT INTO SUPPLIER (name) VALUES ('Browsetype');
INSERT INTO SUPPLIER (name) VALUES ('Fatz');
INSERT INTO SUPPLIER (name) VALUES ('Thoughtsphere');
INSERT INTO SUPPLIER (name) VALUES ('Chatterbridge');
INSERT INTO SUPPLIER (name) VALUES ('Voonte');
INSERT INTO SUPPLIER (name) VALUES ('Wordware');
INSERT INTO SUPPLIER (name) VALUES ('Zoonoodle');
INSERT INTO SUPPLIER (name) VALUES ('Devpoint');
INSERT INTO SUPPLIER (name) VALUES ('Yodoo');
INSERT INTO SUPPLIER (name) VALUES ('Linkbuzz');
INSERT INTO SUPPLIER (name) VALUES ('Thoughtworks');
INSERT INTO SUPPLIER (name) VALUES ('Youbridge');
INSERT INTO SUPPLIER (name) VALUES ('Quatz');
INSERT INTO SUPPLIER (name) VALUES ('Edgetag');
INSERT INTO SUPPLIER (name) VALUES ('Meedoo');
INSERT INTO SUPPLIER (name) VALUES ('Ntags');
INSERT INTO SUPPLIER (name) VALUES ('Thoughtsphere');

INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Beer - Upper Canada Lager', 'Pineapple - Regular', 790.17, 18.03, 6, 1);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Oil - Macadamia', 'Beer - Moosehead', 103.87, 15.61, 7, 1);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Glaze - Apricot', 'Apple - Fuji', 382.21, 9.32, 1, 2);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Veal - Bones', 'Clementine', 507.06, 12.85, 5, 3);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Cake - Box Window 10x10x2.5', 'Cheese - Valancey', 53.96, 4.42, 9, 10);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Wine - Riesling Dr. Pauly', 'Cod - Fillets', 189.62, 18.79, 8, 2);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Sprouts - Alfalfa', 'Sausage - Liver', 276.49, 15.79, 3, 2);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Sauce - Mint', 'Lamb - Whole, Frozen', 655.52, 8.14, 2, 2);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Guava', 'Cheese - Comtomme', 320.57, 10.58, 6, 9);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Cheese - Cheddar With Claret', 'Sprouts Dikon', 928.37, 1.09, 3, 10);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Carrots - Mini, Stem On', 'Wine - Sherry Dry Sack, William', 500.58, 14.03, 1, 9);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Tart - Raisin And Pecan', 'Mace', 270.96, 2.76, 4, 7);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Cheese - Wine', 'Squash - Butternut', 19.34, 17.03, 1, 5);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Dr. Pepper - 355ml', 'Compound - Rum', 494.12, 16.39, 10, 6);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Bread - Calabrese Baguette', 'Plate Pie Foil', 73.65, 4.2, 5, 2);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Coffee - Espresso', 'Bread - Roll, Canadian Dinner', 777.4, 9.5, 4, 4);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Appetizer - Smoked Salmon / Dill', 'Papadam', 492.63, 3.71, 6, 4);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Beef - Flank Steak', 'Energy Drink - Franks Original', 351.98, 5.15, 3, 5);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Salt - Table', 'Pasta - Bauletti, Chicken White', 423.83, 2.68, 2, 6);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Chocolate - Milk, Callets', 'Oregano - Dry, Rubbed', 839.18, 13.55, 3, 4);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Bread - 10 Grain Parisian', 'Wine - Red, Marechal Foch', 821.59, 18.08, 4, 6);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Chocolate - Sugar Free Semi Choc', 'Nescafe - Frothy French Vanilla', 48.35, 15.45, 2, 1);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Lobster - Canned Premium', 'Ocean Spray - Ruby Red', 170.28, 13.93, 6, 6);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Pork - Shoulder', 'Cake - French Pear Tart', 145.14, 15.83, 6, 5);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Bagelers', 'Bag - Regular Kraft 20 Lb', 314.12, 8.02, 2, 1);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Cup - 3.5oz, Foam', 'Dried Apple', 414.85, 9.9, 7, 9);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Chips Potato Reg 43g', 'Mix - Cocktail Strawberry Daiquiri', 305.79, 14.99, 1, 3);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Cheese - Grana Padano', 'Artichokes - Knobless, White', 782.9, 19.21, 6, 8);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Sugar - Brown, Individual', 'Table Cloth 120 Round White', 416.47, 12.98, 2, 6);
INSERT INTO PRODUCT (name, description, price, weight, category_id, supplier_id) VALUES ('Tea - Honey Green Tea', 'Fennel', 642.35, 3.09, 7, 10);

INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (6, 13, 1);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (2, 13, 4);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (3, 9, 4);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (6, 18, 4);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (6, 6, 4);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (5, 23, 1);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (4, 30, 5);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (1, 15, 5);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (6, 11, 4);
INSERT INTO ORDER_DETAIL (order_id, product_id, quantity) VALUES (8, 22, 2);

INSERT INTO STOCK (product_id, location_id, quantity) VALUES (3, 16, 35);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (20, 4, 33);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (5, 20, 50);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (17, 8, 31);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (6, 28, 43);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (9, 14, 0);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (5, 24, 37);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (27, 26, 39);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (1, 12, 37);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (10, 28, 18);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (2, 13, 7);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (23, 13, 3);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (17, 30, 2);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (14, 30, 25);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (1, 3, 20);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (1, 5, 11);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (27, 27, 42);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (30, 30, 19);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (25, 22, 7);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (29, 5, 41);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (2, 28, 10);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (1, 13, 17);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (13, 19, 33);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (12, 14, 36);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (28, 30, 32);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (3, 17, 25);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (4, 7, 39);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (11, 5, 21);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (8, 23, 47);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (5, 3, 27);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (30, 27, 29);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (20, 30, 50);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (9, 15, 18);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (11, 8, 36);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (2, 17, 8);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (10, 29, 6);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (20, 26, 16);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (10, 17, 14);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (6, 12, 25);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (17, 24, 10);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (21, 27, 35);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (3, 23, 40);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (21, 10, 25);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (16, 15, 30);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (13, 5, 1);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (28, 10, 49);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (4, 15, 29);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (10, 8, 43);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (3, 12, 6);
INSERT INTO STOCK (product_id, location_id, quantity) VALUES (25, 27, 43);
